export default {
  apiPrefix: '/api/v1',
  swagger: {
    path: '/api/docs',
    spec: 'openapi.json',
  },
  auth: {
    path: '/auth',
    login: '/login',
    logout: '/logout',
    forgotPassword: '/forgot-password',
    changePassword: '/change-password',
    register: '/register',
    authenticateWithOAuth: '/oauth',
    edit: '/edit',
    verify: '/verify',
    token: '/token',
    me: '/me',
    username: '/user/:username',
    id: '/lookup/:id',
    deleteaccount: '/deleteaccount',
    followers: '/followers/:username',
    following: '/following/:username',
    follow: '/follow/:username',
    unfollow: '/unfollow/:username',
    specificSession: '/session/:id',
    createSession: '/new/session',
    saveSession: '/session/:id/save',
    editSession: '/session/edit',
  },
  post: {
    path: '/post',
  },
};
